### PR TITLE
Send errors to sentry as an Exception

### PR DESCRIPTION
**Pull request by belak**
Logrus has Entry.WithError and an ErrorKey which provides a common place to store errors for logging. This pulls errors out and sends them as an Exception if stack traces are enabled.

It also sets the culprit to the error message (since it's the least intrusive), though my personal preference would be to take the message in the logrus entry, store that as the culprit and place the error message in the outgoing packet message. This still misses a little something, because the culprit from the Stacktrace isn't used, but it doesn't ignore the original message and puts the error message in a more useful location.

### CODE REVIEW

**Comment by belak** [comment]
This is based on some code we used internally (originally based on this code), copied here: https://gist.github.com/belak/3c205bc30a12cef954f57b542abcfb54

**Comment by belak** [comment]
I just realized that this won't work quite yet because all the error values are pulled out and converted to strings.

**Comment by evalphobia** [comment]
@belak  Thanks! I'll check this.

**Comment by evalphobia** [comment]
This works good! 👍 

- disable

sentry01

- enable this feature
sentry02


@belak  Would you rebase&squash all commits into one?
After that I'll merge this 🙆

**Comment by belak** [comment]
Is it a problem that the tags were removed? I'm not 100% sure why it would do that.

**Comment by evalphobia** [comment]
Did you reproduce this tags problem on your environment? 
I don't use this feature actually, so I don't care about it.
But someone might use tag feature. If the problem reproduced on others environment,  I'll send inquiry to Sentry staff.

**Pull request merged**
